//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comman.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketData
    {
        public long Id { get; set; }
        public string ProductTypeID { get; set; }
        public string SymbolName { get; set; }
        public string SymbolCode { get; set; }
        public string QuantTradingType { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> EntryPrice { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public string Result { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
