//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comman.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string ProductName { get; set; }
        public bool IsActive { get; set; }
    }
}
